package ui.graphics;

public enum Sprite {
    FARM_ONE_HEALTH_1,
    FARM_ONE_HEALTH_2,
    FARM_TWO_HEALTH_1,
    FARM_TWO_HEALTH_2,

    MINE_ONE_HEALTH_1,
    MINE_ONE_HEALTH_2,
    MINE_TWO_HEALTH_1,
    MINE_TWO_HEALTH_2,

    PIKEMEN_ONE_HEALTH_1,
    PIKEMEN_ONE_HEALTH_2,
    PIKEMEN_TWO_HEALTH_1,
    PIKEMEN_TWO_HEALTH_2,

    HORSEMEN_ONE_HEALTH_1,
    HORSEMEN_ONE_HEALTH_2,
    HORSEMEN_TWO_HEALTH_1,
    HORSEMEN_TWO_HEALTH_2,

    ARCHER_ONE_HEALTH_1,
    ARCHER_ONE_HEALTH_2,
    ARCHER_TWO_HEALTH_1,
    ARCHER_TWO_HEALTH_2,
}