package lutz.franz.jakob.ui.graphics;

import lutz.franz.jakob.ui.graphics.gui.GUI;

public enum Sprite {
    MEADOW_1,
    MEADOW_2,
    FOREST_1,
    FOREST_2,

    CAPITAL_ONE_HEALTH_1,
    CAPITAL_ONE_HEALTH_2,
    CAPITAL_TWO_HEALTH_1,
    CAPITAL_TWO_HEALTH_2,
    CAPITAL_THREE_HEALTH_1,
    CAPITAL_THREE_HEALTH_2,

    FARM_ONE_HEALTH_1,
    FARM_ONE_HEALTH_2,
    FARM_TWO_HEALTH_1,
    FARM_TWO_HEALTH_2,

    MINE_ONE_HEALTH_1,
    MINE_ONE_HEALTH_2,
    MINE_TWO_HEALTH_1,
    MINE_TWO_HEALTH_2,

    HOUSE_ONE_HEALTH_1,
    HOUSE_ONE_HEALTH_2,
    HOUSE_TWO_HEALTH_1,
    HOUSE_TWO_HEALTH_2,

    PIKEMEN_ONE_HEALTH_1,
    PIKEMEN_ONE_HEALTH_2,
    PIKEMEN_TWO_HEALTH_1,
    PIKEMEN_TWO_HEALTH_2,

    HORSEMEN_ONE_HEALTH_1,
    HORSEMEN_ONE_HEALTH_2,
    HORSEMEN_TWO_HEALTH_1,
    HORSEMEN_TWO_HEALTH_2,

    ARCHER_ONE_HEALTH_1,
    ARCHER_ONE_HEALTH_2,
    ARCHER_TWO_HEALTH_1,
    ARCHER_TWO_HEALTH_2;

    public static final int SIZE = 16 * GUI.RESCALE_FACTOR;
}